import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/AOSInit";
import { DrawCircleText } from "@/components/ui/DrawCircleText";
import Navbar from "./layout/Navbar";
import Footer from "./layout/Footer";
import SectionModal from "./home/SectionModal";
import Providers from "@/app/store/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RTK Query Setup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full   max-md:px-4 overflow-x-hidden flex flex-col">
        {/* <AOSInit /> */}
        <Navbar />
        <Providers>
          {children} <SectionModal />
        </Providers>
        <footer>
          <DrawCircleText />
          <Footer />
        </footer>
      </body>
    </html>
  );
}
