import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/AOSInit";
import { DrawCircleText } from "@/components/ui/DrawCircleText";

import Providers from "@/app/store/Providers";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FoodHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="min-h-full dark:bg-[#030423]   overflow-x-hidden flex flex-col"
      >
        {/* <AOSInit /> */}
        {/* <Navbar /> */}
        <Providers>{children}</Providers>
        {/* <footer>
          <DrawCircleText />
          <Footer />
        </footer> */}
      </body>
    </html>
  );
}
